[project]
name = "synthetic-meat"
version = "0.1.0"
description = "Synthetic data generator for meat processing data."
requires-python = ">=3.11"
dependencies = [
    "polars[pandas]>=0.20.0",
    "pyarrow>=15.0.0",
    "faker>=20.0.0",
    "gcsfs>=2023.0.0",
    "google-cloud-storage>=2.0.0",
    "openpyxl>=3.1.0", # For reading xlsx with polars
    "functions-framework>=3.0.0",
    "fastparquet>=2024.2.0",
    "requests>=2.30.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
]

[tool.pytest.ini_options]
pythonpath = "src"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
