name: Deploy DAGs to Composer

on:
  push:
    branches:
      - main
    paths:
      - 'dag/**.py'
      - '.github/workflows/dag.yml'
  workflow_dispatch:

env:
  # COMPOSER_BUCKET is set manually in GitHub Secrets. Use the name of the
  # bucket found in the Composer configuration page under
  # 'DAGs folder' (stripped of the /dags and gs://).
  COMPOSER_BUCKET: ${{ secrets.COMPOSER_BUCKET }}
  # This is being set manually too
  DEPS_BUCKET: ${{ secrets.DEPS_BUCKET }}

jobs:
  deploy:
    name: Test and deploy DAGs
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up uv
      uses: astral-sh/setup-uv@v7

    - name: Install dependencies
      working-directory: ./dag
      run: |
        uv venv
        uv sync --locked --group test

    - name: Run tests
      working-directory: ./dag
      run: |
        uv run pytest -v

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
        audience: 'sts.googleapis.com'

    - name: Sync DAGs to Composer
      run: |
        gcloud storage rsync dag/src/ "gs://${{ env.COMPOSER_BUCKET }}/dags/" \
        --delete-unmatched-destination-objects --recursive \
        --exclude "airflow_monitoring.py"
        gcloud storage rsync dag/spark_jobs/ "gs://${{ env.DEPS_BUCKET }}/spark_jobs/" \
        --delete-unmatched-destination-objects --recursive
