name: Deploy DAGs to Composer

on:
  push:
    branches:
      - main
    paths:
      - 'dag/**'
      - '.github/workflows/dag.yml'

env:
  COMPOSER_BUCKET: ${{ secrets.COMPOSER_BUCKET }}

jobs:
  deploy:
    name: Sync DAGs
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
        audience: 'sts.googleapis.com'

    - name: Debug Composer Bucket
      run: |
        echo "COMPOSER_BUCKET=${{ env.COMPOSER_BUCKET }}"
        gsutil ls "${{ env.COMPOSER_BUCKET }}"
        gsutil iam get "(echo ${{ env.COMPOSER_BUCKET }} | SED 'S|/DAGS.*||')"
    - name: Sync DAGs to Composer
      run: gsutil rsync -d dag "${{ env.COMPOSER_BUCKET }}"
