name: Deploy Warehouse Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'warehouse/**'
      - '.github/workflows/deploy.yml'
      - 'ingestion/synthetic-meat/**'

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GAR_REPOSITORY: 'meat-data-images'
  IMAGE_NAME: 'synthetic-meat'

jobs:
  deploy:
    name: Deploy Warehouse
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
        audience: 'sts.googleapis.com'

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

    - name: Build and Push Docker Image
      id: build-image
      run: |
        IMAGE_URI="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        docker build -t $IMAGE_URI ./ingestion/synthetic-meat
        docker push $IMAGE_URI
        echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: latest

    - name: Tofu Init
      id: init
      run: |
        tofu init -upgrade -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="prefix=${GCP_PROJECT_ID}/warehouse"
      working-directory: warehouse

    - name: Tofu Plan
      id: plan
      run: tofu plan -var="project_id=${GCP_PROJECT_ID}" -var="region=${GCP_REGION}" -var="app_engine_region=${{ secrets.GCP_APP_ENGINE_REGION }}" -var="image_uri=${{ steps.build-image.outputs.image_uri }}" -out=tfplan
      working-directory: warehouse

    - name: Tofu Apply
      run: tofu apply -auto-approve tfplan
      working-directory: warehouse
